theme = "autumn"

[editor]
auto-save = true
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
mouse = true
auto-format = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[keys.normal]
# C-p = ["move_line_up", "scroll_up"]
# C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.insert]
# j = { k = "normal_mode" }
# k = { j = "normal_mode" }
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "file-encoding", "file-type", "position", "position-percentage", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"