theme = "autumn"

[editor]
scrolloff = 10
auto-save = true
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
mouse = true
auto-format = true
# undercurl = true

[editor.indent-guides]
# render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
# esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
w = ":write"
# q = ":quit"
c = ":buffer-close"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.insert.j]
j = "normal_mode"
k = "normal_mode"

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "workspace-diagnostics", "spacer", "spinner"]
center = ["file-name", "spacer", "diagnostics"]
right = ["file-type", "spacer",  "position-percentage", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"