theme = "gruvbox_light"

[editor]
auto-save = true
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
mouse = true
auto-format = true
# rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [[language]]
# name = "rust"
# auto-format = true