theme = "catppuccin_macchiato"

[editor]
auto-save = true
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
mouse = true
auto-format = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[keys.normal]
# C-s = ":w"
# C-q = ":q"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "file-encoding", "file-type", "position", "position-percentage", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"